### ISSUE TITLE
SAAS Wireframe

### ISSUE THREAD

**Issue by char1129** [char1129/saas-website#1]
@muxlowc 
Sorry in advance about how this came out. If you'd rather me retype it all out I will. I'm just trying to maximize my time efficiently and had issues exporting this from Excel like I originally wanted to.

Thanks!
@char1129 

[
[charity-sarah-040-SAASwireframe.pdf](https://github.com/char1129/saas-website/files/4452238/charity-sarah-040-SAASwireframe.pdf)
](url)

**Comment by muxlowc** [comment]
@char1129 This looks great - just make sure you have a table on your tour.html ("services") page - it doesn't have to be complicated

**Comment by char1129** [comment]
@muxlowc  Thank you! I'll start building asap 😊
