### ISSUE TITLE
One last error - Main link focus - background of links in main content not changing

### ISSUE THREAD

**Issue by char1129** [char1129/saas-website#4]
Hello again,

I decided to change around the way my nav works and resolved all but 1 of my god-forsaken issues. Could you take a look and tell me why its only on  my tour page and what I can do to fix it?
(Note: I did add outline-colours to all focus to see if that'd help but didnt.)

Thanks...

@muxlowc
@mackenzierose
@char1129 
![help3](https://user-images.githubusercontent.com/55107755/79906971-d35c9c00-83e6-11ea-8fbc-185076be565c.JPG)

**Comment by muxlowc** [comment]
@char1129 Yah I can't seem to figure out what the issue is. Everything seems to have a focus from what I see. Sorry, but I think I might have to manually add in your markbot grade! - Just submit a screenshot of markbot when you request you grade.
